[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2018"

[lib]
crate-type = ["cdylib"]


[package.metadata.wasmcloud]
capabilities = [
]

[dependencies]
wapc-guest = "0.4.0"
wasmcloud-actor-core = { version = "0.2.2", features = ["guest"] }

[profile.release]
# Optimize for small code size
opt-level = "s"
lto = true
